"""create table categories

Revision ID: 978be429f070
Revises: 7793536980bd
Create Date: 2024-02-08 15:47:10.263613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978be429f070'
down_revision = '7793536980bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('title', name=op.f('uq_categories_title'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
