"""create association table articles_tags

Revision ID: cff0fe59728e
Revises: 77f56fbda560
Create Date: 2024-02-08 16:36:44.744619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff0fe59728e'
down_revision = '77f56fbda560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_articles_tags_article_id_articles')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_articles_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_articles_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_tags')
    # ### end Alembic commands ###
